# Basic
title: TonyScript
subtitle: 嗨，我是@TonyScript，一名iOS开发者，现居上海。正在路上，去往更大的世界。
#welcome_message: <a href="https://github.com/hexoishexo" target="_blank">Download the theme</a>
description: 人生真是寂寞如雪啊。
creator: <a href="https://www.github.com/TonyScript">@TonyScript</a>

url: "https://github.com/TonyScript"

permalink: /:year/:month/:title/

# Format
highlighter: plain
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://github.com/TonyScript'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo:  TonyScript
    github:  TonyScript
    twitter:  TonyScript
    facebook:  jimoruxue
    mail: TonyScript@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
